sudo: required
services:
    - docker

before_install:
    - docker build -t pakdboth/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true pakdboth/docker-react npm run test -- --coverage
